if(!Accounts.findUserByEmail('malbu@my.centennialcollege.ca')){  
  Accounts.createUser({ email: 'taggarw1@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Tarun Aggarwal'}});
  Accounts.createUser({ email: 'bakhtar2@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Bilkis Akhtar'}});
  Accounts.createUser({ email: 'malbu@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Mihai Albu'}});
  Accounts.createUser({ email: 'panil1@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Pranoy Anil'}});
  Accounts.createUser({ email: 'gbenipa3@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Gurpreet Benipal'}});
  Accounts.createUser({ email: 'zcai9@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Zhaoning Cai'}});
  Accounts.createUser({ email: 'nchernyk@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Nikita Chernykh'}});
  Accounts.createUser({ email: 'fcipria2@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Felix Cipriani'}});
  Accounts.createUser({ email: 'wdogar@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Waleed Dogar'}});
  Accounts.createUser({ email: 'jgozarat@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'James Gozarate'}});
  Accounts.createUser({ email: 'ajuneja3@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Anjali Juneja'}});
  Accounts.createUser({ email: 'ikaur23@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Inderpal Kaur'}});
  Accounts.createUser({ email: 'kkaur160@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Kamalpreet Kaur'}});
  Accounts.createUser({ email: 'skaur228@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Surpreet Kaur'}});
  Accounts.createUser({ email: 'tkaur30@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Tavleen Kaur'}});
  Accounts.createUser({ email: 'skuppa@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Sruthi Kuppa'}});
  Accounts.createUser({ email: 'hlac@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Hao Lac'}});
  Accounts.createUser({ email: 'zli141@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Zhen Li'}});
  Accounts.createUser({ email: 'gomar4@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Ga-Alo Omar'}});
  Accounts.createUser({ email: 'spanch32@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Sachet Panchal'}});
  Accounts.createUser({ email: 'jparnel1@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Jacob Parnell'}});
  Accounts.createUser({ email: 'dpate430@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Divyeshkumar Patel'}});
  Accounts.createUser({ email: 'hpate322@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Harshkumar Patel'}});
  Accounts.createUser({ email: 'aprajap5@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Anant Prajapati'}});
  Accounts.createUser({ email: 'apulivar@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Ashish Pulivarthi'}});
  Accounts.createUser({ email: 'lralh@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Lovepreet Ralh'}});
  Accounts.createUser({ email: 'ztoulous@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Zachariah Toulouse'}});
  Accounts.createUser({ email: 'svelaga1@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Sai Sravani Velaga'}});
  Accounts.createUser({ email: 'kverma6@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Karanvir Verma'}});
  Accounts.createUser({ email: 'mverma15@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Milan Verma'}});
  Accounts.createUser({ email: 'wwang134@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Wei Wang'}});
  Accounts.createUser({ email: 'awatanab@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Alexandre Watanabe'}});
  Accounts.createUser({ email: 'lxu43@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Li Xu'}});
  Accounts.createUser({ email: 'czhao25@my.centennialcollege.ca' ,  password: 'test', profile: { fullName: 'Chenyu Zhao'}});
}
